wip

diff --git a/.local/bin/streamdeck-start b/.local/bin/streamdeck-start
--- a/.local/bin/streamdeck-start
+++ b/.local/bin/streamdeck-start
@@ -1,10 +1,37 @@
 #!/bin/sh
 
+# if ! streamdeck; then
+#     #echo "Failed to start Streamdeck UI"
+#     notify-send "streamdeck failed to start"
+#     #exit 1
+# fi
+#
+# window_id=
+# timeout=5000
+# while [ -z "$window_id" ] && [ "$timeout" -gt 0 ]; do
+#     sleep 0.1
+#     window_id=$(xdotool search --class "Streamdeck UI" | head -n 1)
+#     ((timeout--))
+# done
+#
+# if [ -z "$window_id" ]; then
+#     notify-send "Timed out waiting for Streamdeck UI window to appear"
+#     exit 1
+# fi
+#
+# notify-send "timeout=$timeout"
+#
+# if ! xdotool windowactivate "Streamdeck UI" windowminimize; then
+#     notify-send "Failed to minimize Streamdeck UI"
+#     exit 1
+# fi
+
 if command -v streamdeck; then
-  echo 'exec streamdeck &'
-  nohup streamdeck &
+  streamdeck & sleep 2 && xdotool search --class "Streamdeck UI" windowminimize
 else
   notify-send "streamdeck is NOT installed"
 fi
+
+# xdotool search --onlyvisible --class "Streamdeck UI"
 
 exit 0
